name: Version

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Choose the type of semantic version bump.'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Bump Version
      shell: pwsh
      run: |
        $xml = [Xml] (Get-Content ./Streakathon.MAUI/Streakathon.MAUI.csproj)
        $version = [Version] $xml.Project.PropertyGroup.ApplicationDisplayVersion

        $major = $version.Major
        $minor = $version.Minor
        $patch = $version.Build

        switch("${{ inputs.versionType }}") 
        {
            "major"
            {
                $major = $major + 1
            }
            "minor"
            {
                $minor = $minor + 1
            }
            "patch"
            {
                $patch = $patch + 1
            }
        }

        $newVersion = "{0}.{1}.{2}" -f $major, $minor, $patch
        $xml.Project.PropertyGroup.ApplicationDisplayVersion = $newVersion
        $xml.Save("./Streakathon.MAUI/Streakathon.MAUI.csproj")

    - name: Commit Version Bump
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add ./Streakathon.MAUI/Streakathon.MAUI.csproj
        git commit -m "Bump version"

    - name: Push Version Bump
      run: |
        git push origin master

    - name: Master -> Release
      run: |
        git checkout -b release
        git pull origin release
        git merge master
        git push origin release


