name: Version

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Install NPM Packages
      run: npm ci
      working-directory: ./Streakathon.MAUI

    - name: Bump Version
      run: npm run version
      working-directory: ./Streakathon.MAUI

    - name: Sync Changesets Version
      shell: pwsh
      run: |
        $package = Get-Content -Raw ./Streakathon.MAUI/package.json | ConvertFrom-Json
        $version = $package.version

        $xml = [Xml] (Get-Content ./Streakathon.MAUI/Streakathon.MAUI.csproj)
        $xml.Project.PropertyGroup.ApplicationDisplayVersion = $version
        $xml.Save("./Streakathon.MAUI/Streakathon.MAUI.csproj")

        $appinstallerXml = [Xml] (Get-Content ./Streakathon.MAUI/Streakathon.appinstaller)
        $appinstallerNewVersion = "{0}.0" -f $version
        $appinstallerXml.AppInstaller.MainPackage.Version = $appinstallerNewVersion
        $appinstallerXml.Save("./Streakathon.MAUI/Streakathon.appinstaller")

    - name: Commit Version Bump
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add ./Streakathon.MAUI/Streakathon.MAUI.csproj
        git add ./Streakathon.MAUI/Streakathon.appinstaller
        git add ./Streakathon.MAUI/CHANGELOG.md
        git add ./Streakathon.MAUI/.changeset
        git add ./Streakathon.MAUI/package.json
        git commit -m "Bump version"

    - name: Push Version Bump
      run: |
        git push origin master

    - name: Master -> Release
      run: |
        git fetch origin release
        git checkout -b release origin/release
        git merge master
        git push origin release
