name: Version

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Install NPM Packages
      run: npm ci
      working-directory: ./Streakathon.MAUI

    - name: Create Release Pull Request
      uses: changesets/action@v1
      with:
        cwd: ./Streakathon.MAUI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync Changesets Version
      shell: pwsh
      run: |
        $package = Get-Content -Raw ./Streakathon.MAUI/package.json | ConvertFrom-Json
        $version = $package.version

        $xml = [Xml] (Get-Content ./Streakathon.MAUI/Streakathon.MAUI.csproj)
        $xml.Project.PropertyGroup.ApplicationDisplayVersion = $version
        $xml.Save("./Streakathon.MAUI/Streakathon.MAUI.csproj")

        $appinstallerXml = [Xml] (Get-Content ./Streakathon.MAUI/Streakathon.appinstaller)
        $appinstallerNewVersion = "{0}.0" -f $version
        $appinstallerXml.AppInstaller.MainPackage.Version = $appinstallerNewVersion
        $appinstallerXml.Save("./Streakathon.MAUI/Streakathon.appinstaller")

    - name: Commit Version Bump
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit --amend --no-verify

    - name: Push Version Bump
      run: git push origin version
